# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server import util


class AnnouncementReqDto(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, content: str=None):
        """AnnouncementReqDto - a model defined in OpenAPI

        :param content: The content of this AnnouncementReqDto.
        """
        self.openapi_types = {
            'content': str
        }

        self.attribute_map = {
            'content': 'content'
        }

        self._content = content

    @classmethod
    def from_dict(cls, dikt: dict) -> 'AnnouncementReqDto':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The AnnouncementReqDto of this AnnouncementReqDto.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def content(self):
        """Gets the content of this AnnouncementReqDto.


        :return: The content of this AnnouncementReqDto.
        :rtype: str
        """
        return self._content

    @content.setter
    def content(self, content):
        """Sets the content of this AnnouncementReqDto.


        :param content: The content of this AnnouncementReqDto.
        :type content: str
        """
        if content is None:
            raise ValueError("Invalid value for `content`, must not be `None`")

        self._content = content
