# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server import util


class AuthTokenResDto(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, access_token: str=None):
        """AuthTokenResDto - a model defined in OpenAPI

        :param access_token: The access_token of this AuthTokenResDto.
        """
        self.openapi_types = {
            'access_token': str
        }

        self.attribute_map = {
            'access_token': 'accessToken'
        }

        self._access_token = access_token

    @classmethod
    def from_dict(cls, dikt: dict) -> 'AuthTokenResDto':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The AuthTokenResDto of this AuthTokenResDto.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def access_token(self):
        """Gets the access_token of this AuthTokenResDto.


        :return: The access_token of this AuthTokenResDto.
        :rtype: str
        """
        return self._access_token

    @access_token.setter
    def access_token(self, access_token):
        """Sets the access_token of this AuthTokenResDto.


        :param access_token: The access_token of this AuthTokenResDto.
        :type access_token: str
        """
        if access_token is None:
            raise ValueError("Invalid value for `access_token`, must not be `None`")

        self._access_token = access_token
