# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server import util


class Content(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, type: str=None, data: str=None):
        """Content - a model defined in OpenAPI

        :param type: The type of this Content.
        :param data: The data of this Content.
        """
        self.openapi_types = {
            'type': str,
            'data': str
        }

        self.attribute_map = {
            'type': 'type',
            'data': 'data'
        }

        self._type = type
        self._data = data

    @classmethod
    def from_dict(cls, dikt: dict) -> 'Content':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The Content of this Content.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self):
        """Gets the type of this Content.


        :return: The type of this Content.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Content.


        :param type: The type of this Content.
        :type type: str
        """
        allowed_values = ["text", "file"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def data(self):
        """Gets the data of this Content.


        :return: The data of this Content.
        :rtype: str
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this Content.


        :param data: The data of this Content.
        :type data: str
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")

        self._data = data
