# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server import util


class ConversationColorReqDto(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, color_label: str=None):
        """ConversationColorReqDto - a model defined in OpenAPI

        :param color_label: The color_label of this ConversationColorReqDto.
        """
        self.openapi_types = {
            'color_label': str
        }

        self.attribute_map = {
            'color_label': 'colorLabel'
        }

        self._color_label = color_label

    @classmethod
    def from_dict(cls, dikt: dict) -> 'ConversationColorReqDto':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The ConversationColorReqDto of this ConversationColorReqDto.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def color_label(self):
        """Gets the color_label of this ConversationColorReqDto.


        :return: The color_label of this ConversationColorReqDto.
        :rtype: str
        """
        return self._color_label

    @color_label.setter
    def color_label(self, color_label):
        """Sets the color_label of this ConversationColorReqDto.


        :param color_label: The color_label of this ConversationColorReqDto.
        :type color_label: str
        """
        if color_label is None:
            raise ValueError("Invalid value for `color_label`, must not be `None`")
        if color_label is not None and len(color_label) > 32:
            raise ValueError("Invalid value for `color_label`, length must be less than or equal to `32`")

        self._color_label = color_label
