# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server.models.message import Message
from openapi_server.models.user_res_dto import UserResDto
from openapi_server import util


class ConversationResDto(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id: float=None, name: str=None, messages: List[Message]=None, users: List[UserResDto]=None, updated_at: datetime=None, is_public: bool=None, color_label: str=None, version: float=None):
        """ConversationResDto - a model defined in OpenAPI

        :param id: The id of this ConversationResDto.
        :param name: The name of this ConversationResDto.
        :param messages: The messages of this ConversationResDto.
        :param users: The users of this ConversationResDto.
        :param updated_at: The updated_at of this ConversationResDto.
        :param is_public: The is_public of this ConversationResDto.
        :param color_label: The color_label of this ConversationResDto.
        :param version: The version of this ConversationResDto.
        """
        self.openapi_types = {
            'id': float,
            'name': str,
            'messages': List[Message],
            'users': List[UserResDto],
            'updated_at': datetime,
            'is_public': bool,
            'color_label': str,
            'version': float
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'messages': 'messages',
            'users': 'users',
            'updated_at': 'updatedAt',
            'is_public': 'isPublic',
            'color_label': 'colorLabel',
            'version': 'version'
        }

        self._id = id
        self._name = name
        self._messages = messages
        self._users = users
        self._updated_at = updated_at
        self._is_public = is_public
        self._color_label = color_label
        self._version = version

    @classmethod
    def from_dict(cls, dikt: dict) -> 'ConversationResDto':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The ConversationResDto of this ConversationResDto.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this ConversationResDto.


        :return: The id of this ConversationResDto.
        :rtype: float
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ConversationResDto.


        :param id: The id of this ConversationResDto.
        :type id: float
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")

        self._id = id

    @property
    def name(self):
        """Gets the name of this ConversationResDto.


        :return: The name of this ConversationResDto.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ConversationResDto.


        :param name: The name of this ConversationResDto.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")

        self._name = name

    @property
    def messages(self):
        """Gets the messages of this ConversationResDto.


        :return: The messages of this ConversationResDto.
        :rtype: List[Message]
        """
        return self._messages

    @messages.setter
    def messages(self, messages):
        """Sets the messages of this ConversationResDto.


        :param messages: The messages of this ConversationResDto.
        :type messages: List[Message]
        """
        if messages is None:
            raise ValueError("Invalid value for `messages`, must not be `None`")

        self._messages = messages

    @property
    def users(self):
        """Gets the users of this ConversationResDto.


        :return: The users of this ConversationResDto.
        :rtype: List[UserResDto]
        """
        return self._users

    @users.setter
    def users(self, users):
        """Sets the users of this ConversationResDto.


        :param users: The users of this ConversationResDto.
        :type users: List[UserResDto]
        """
        if users is None:
            raise ValueError("Invalid value for `users`, must not be `None`")

        self._users = users

    @property
    def updated_at(self):
        """Gets the updated_at of this ConversationResDto.


        :return: The updated_at of this ConversationResDto.
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this ConversationResDto.


        :param updated_at: The updated_at of this ConversationResDto.
        :type updated_at: datetime
        """
        if updated_at is None:
            raise ValueError("Invalid value for `updated_at`, must not be `None`")

        self._updated_at = updated_at

    @property
    def is_public(self):
        """Gets the is_public of this ConversationResDto.


        :return: The is_public of this ConversationResDto.
        :rtype: bool
        """
        return self._is_public

    @is_public.setter
    def is_public(self, is_public):
        """Sets the is_public of this ConversationResDto.


        :param is_public: The is_public of this ConversationResDto.
        :type is_public: bool
        """
        if is_public is None:
            raise ValueError("Invalid value for `is_public`, must not be `None`")

        self._is_public = is_public

    @property
    def color_label(self):
        """Gets the color_label of this ConversationResDto.


        :return: The color_label of this ConversationResDto.
        :rtype: str
        """
        return self._color_label

    @color_label.setter
    def color_label(self, color_label):
        """Sets the color_label of this ConversationResDto.


        :param color_label: The color_label of this ConversationResDto.
        :type color_label: str
        """
        if color_label is None:
            raise ValueError("Invalid value for `color_label`, must not be `None`")

        self._color_label = color_label

    @property
    def version(self):
        """Gets the version of this ConversationResDto.


        :return: The version of this ConversationResDto.
        :rtype: float
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this ConversationResDto.


        :param version: The version of this ConversationResDto.
        :type version: float
        """
        if version is None:
            raise ValueError("Invalid value for `version`, must not be `None`")

        self._version = version
