# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server import util


class MarkdownResDto(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id: float=None, title: str=None, content: str=None, updated_at: datetime=None, version: float=None):
        """MarkdownResDto - a model defined in OpenAPI

        :param id: The id of this MarkdownResDto.
        :param title: The title of this MarkdownResDto.
        :param content: The content of this MarkdownResDto.
        :param updated_at: The updated_at of this MarkdownResDto.
        :param version: The version of this MarkdownResDto.
        """
        self.openapi_types = {
            'id': float,
            'title': str,
            'content': str,
            'updated_at': datetime,
            'version': float
        }

        self.attribute_map = {
            'id': 'id',
            'title': 'title',
            'content': 'content',
            'updated_at': 'updatedAt',
            'version': 'version'
        }

        self._id = id
        self._title = title
        self._content = content
        self._updated_at = updated_at
        self._version = version

    @classmethod
    def from_dict(cls, dikt: dict) -> 'MarkdownResDto':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The MarkdownResDto of this MarkdownResDto.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this MarkdownResDto.


        :return: The id of this MarkdownResDto.
        :rtype: float
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this MarkdownResDto.


        :param id: The id of this MarkdownResDto.
        :type id: float
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")

        self._id = id

    @property
    def title(self):
        """Gets the title of this MarkdownResDto.


        :return: The title of this MarkdownResDto.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this MarkdownResDto.


        :param title: The title of this MarkdownResDto.
        :type title: str
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")

        self._title = title

    @property
    def content(self):
        """Gets the content of this MarkdownResDto.


        :return: The content of this MarkdownResDto.
        :rtype: str
        """
        return self._content

    @content.setter
    def content(self, content):
        """Sets the content of this MarkdownResDto.


        :param content: The content of this MarkdownResDto.
        :type content: str
        """
        if content is None:
            raise ValueError("Invalid value for `content`, must not be `None`")

        self._content = content

    @property
    def updated_at(self):
        """Gets the updated_at of this MarkdownResDto.


        :return: The updated_at of this MarkdownResDto.
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this MarkdownResDto.


        :param updated_at: The updated_at of this MarkdownResDto.
        :type updated_at: datetime
        """
        if updated_at is None:
            raise ValueError("Invalid value for `updated_at`, must not be `None`")

        self._updated_at = updated_at

    @property
    def version(self):
        """Gets the version of this MarkdownResDto.


        :return: The version of this MarkdownResDto.
        :rtype: float
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this MarkdownResDto.


        :param version: The version of this MarkdownResDto.
        :type version: float
        """
        if version is None:
            raise ValueError("Invalid value for `version`, must not be `None`")

        self._version = version
