# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server import util


class MarkdownReqDto(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, title: str=None, content: str=None):
        """MarkdownReqDto - a model defined in OpenAPI

        :param title: The title of this MarkdownReqDto.
        :param content: The content of this MarkdownReqDto.
        """
        self.openapi_types = {
            'title': str,
            'content': str
        }

        self.attribute_map = {
            'title': 'title',
            'content': 'content'
        }

        self._title = title
        self._content = content

    @classmethod
    def from_dict(cls, dikt: dict) -> 'MarkdownReqDto':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The MarkdownReqDto of this MarkdownReqDto.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def title(self):
        """Gets the title of this MarkdownReqDto.


        :return: The title of this MarkdownReqDto.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this MarkdownReqDto.


        :param title: The title of this MarkdownReqDto.
        :type title: str
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")

        self._title = title

    @property
    def content(self):
        """Gets the content of this MarkdownReqDto.


        :return: The content of this MarkdownReqDto.
        :rtype: str
        """
        return self._content

    @content.setter
    def content(self, content):
        """Sets the content of this MarkdownReqDto.


        :param content: The content of this MarkdownReqDto.
        :type content: str
        """
        if content is None:
            raise ValueError("Invalid value for `content`, must not be `None`")

        self._content = content
