# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server import util


class UserReqDto(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, username: str=None, email: str=None, password: str=None):
        """UserReqDto - a model defined in OpenAPI

        :param username: The username of this UserReqDto.
        :param email: The email of this UserReqDto.
        :param password: The password of this UserReqDto.
        """
        self.openapi_types = {
            'username': str,
            'email': str,
            'password': str
        }

        self.attribute_map = {
            'username': 'username',
            'email': 'email',
            'password': 'password'
        }

        self._username = username
        self._email = email
        self._password = password

    @classmethod
    def from_dict(cls, dikt: dict) -> 'UserReqDto':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The UserReqDto of this UserReqDto.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def username(self):
        """Gets the username of this UserReqDto.


        :return: The username of this UserReqDto.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this UserReqDto.


        :param username: The username of this UserReqDto.
        :type username: str
        """
        if username is None:
            raise ValueError("Invalid value for `username`, must not be `None`")

        self._username = username

    @property
    def email(self):
        """Gets the email of this UserReqDto.


        :return: The email of this UserReqDto.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this UserReqDto.


        :param email: The email of this UserReqDto.
        :type email: str
        """
        if email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")

        self._email = email

    @property
    def password(self):
        """Gets the password of this UserReqDto.


        :return: The password of this UserReqDto.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this UserReqDto.


        :param password: The password of this UserReqDto.
        :type password: str
        """
        if password is None:
            raise ValueError("Invalid value for `password`, must not be `None`")

        self._password = password
