# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server import util


class UserEmailReqDto(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, email: str=None):
        """UserEmailReqDto - a model defined in OpenAPI

        :param email: The email of this UserEmailReqDto.
        """
        self.openapi_types = {
            'email': str
        }

        self.attribute_map = {
            'email': 'email'
        }

        self._email = email

    @classmethod
    def from_dict(cls, dikt: dict) -> 'UserEmailReqDto':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The UserEmailReqDto of this UserEmailReqDto.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def email(self):
        """Gets the email of this UserEmailReqDto.


        :return: The email of this UserEmailReqDto.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this UserEmailReqDto.


        :param email: The email of this UserEmailReqDto.
        :type email: str
        """
        if email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")

        self._email = email
