# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server import util


class UserUsernameReqDto(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, username: str=None):
        """UserUsernameReqDto - a model defined in OpenAPI

        :param username: The username of this UserUsernameReqDto.
        """
        self.openapi_types = {
            'username': str
        }

        self.attribute_map = {
            'username': 'username'
        }

        self._username = username

    @classmethod
    def from_dict(cls, dikt: dict) -> 'UserUsernameReqDto':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The UserUsernameReqDto of this UserUsernameReqDto.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def username(self):
        """Gets the username of this UserUsernameReqDto.


        :return: The username of this UserUsernameReqDto.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this UserUsernameReqDto.


        :param username: The username of this UserUsernameReqDto.
        :type username: str
        """
        if username is None:
            raise ValueError("Invalid value for `username`, must not be `None`")

        self._username = username
