# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server import util


class UserPrivilegesReqDto(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, username: str=None, email_verified: bool=None, roles: List[str]=None, credit: float=None):
        """UserPrivilegesReqDto - a model defined in OpenAPI

        :param username: The username of this UserPrivilegesReqDto.
        :param email_verified: The email_verified of this UserPrivilegesReqDto.
        :param roles: The roles of this UserPrivilegesReqDto.
        :param credit: The credit of this UserPrivilegesReqDto.
        """
        self.openapi_types = {
            'username': str,
            'email_verified': bool,
            'roles': List[str],
            'credit': float
        }

        self.attribute_map = {
            'username': 'username',
            'email_verified': 'emailVerified',
            'roles': 'roles',
            'credit': 'credit'
        }

        self._username = username
        self._email_verified = email_verified
        self._roles = roles
        self._credit = credit

    @classmethod
    def from_dict(cls, dikt: dict) -> 'UserPrivilegesReqDto':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The UserPrivilegesReqDto of this UserPrivilegesReqDto.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def username(self):
        """Gets the username of this UserPrivilegesReqDto.


        :return: The username of this UserPrivilegesReqDto.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this UserPrivilegesReqDto.


        :param username: The username of this UserPrivilegesReqDto.
        :type username: str
        """
        if username is None:
            raise ValueError("Invalid value for `username`, must not be `None`")

        self._username = username

    @property
    def email_verified(self):
        """Gets the email_verified of this UserPrivilegesReqDto.


        :return: The email_verified of this UserPrivilegesReqDto.
        :rtype: bool
        """
        return self._email_verified

    @email_verified.setter
    def email_verified(self, email_verified):
        """Sets the email_verified of this UserPrivilegesReqDto.


        :param email_verified: The email_verified of this UserPrivilegesReqDto.
        :type email_verified: bool
        """
        if email_verified is None:
            raise ValueError("Invalid value for `email_verified`, must not be `None`")

        self._email_verified = email_verified

    @property
    def roles(self):
        """Gets the roles of this UserPrivilegesReqDto.


        :return: The roles of this UserPrivilegesReqDto.
        :rtype: List[str]
        """
        return self._roles

    @roles.setter
    def roles(self, roles):
        """Sets the roles of this UserPrivilegesReqDto.


        :param roles: The roles of this UserPrivilegesReqDto.
        :type roles: List[str]
        """
        allowed_values = ["user", "admin"]  # noqa: E501
        if not set(roles).issubset(set(allowed_values)):
            raise ValueError(
                "Invalid values for `roles` [{0}], must be a subset of [{1}]"
                .format(", ".join(map(str, set(roles) - set(allowed_values))),
                        ", ".join(map(str, allowed_values)))
            )

        self._roles = roles

    @property
    def credit(self):
        """Gets the credit of this UserPrivilegesReqDto.


        :return: The credit of this UserPrivilegesReqDto.
        :rtype: float
        """
        return self._credit

    @credit.setter
    def credit(self, credit):
        """Sets the credit of this UserPrivilegesReqDto.


        :param credit: The credit of this UserPrivilegesReqDto.
        :type credit: float
        """
        if credit is None:
            raise ValueError("Invalid value for `credit`, must not be `None`")

        self._credit = credit
