# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server import util


class UserAvatarReqDto(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, avatar: str=None):
        """UserAvatarReqDto - a model defined in OpenAPI

        :param avatar: The avatar of this UserAvatarReqDto.
        """
        self.openapi_types = {
            'avatar': str
        }

        self.attribute_map = {
            'avatar': 'avatar'
        }

        self._avatar = avatar

    @classmethod
    def from_dict(cls, dikt: dict) -> 'UserAvatarReqDto':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The UserAvatarReqDto of this UserAvatarReqDto.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def avatar(self):
        """Gets the avatar of this UserAvatarReqDto.


        :return: The avatar of this UserAvatarReqDto.
        :rtype: str
        """
        return self._avatar

    @avatar.setter
    def avatar(self, avatar):
        """Sets the avatar of this UserAvatarReqDto.


        :param avatar: The avatar of this UserAvatarReqDto.
        :type avatar: str
        """
        if avatar is None:
            raise ValueError("Invalid value for `avatar`, must not be `None`")

        self._avatar = avatar
