# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server import util


class WebUrlResDto(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, web_url: str=None):
        """WebUrlResDto - a model defined in OpenAPI

        :param web_url: The web_url of this WebUrlResDto.
        """
        self.openapi_types = {
            'web_url': str
        }

        self.attribute_map = {
            'web_url': 'webUrl'
        }

        self._web_url = web_url

    @classmethod
    def from_dict(cls, dikt: dict) -> 'WebUrlResDto':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The WebUrlResDto of this WebUrlResDto.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def web_url(self):
        """Gets the web_url of this WebUrlResDto.


        :return: The web_url of this WebUrlResDto.
        :rtype: str
        """
        return self._web_url

    @web_url.setter
    def web_url(self, web_url):
        """Sets the web_url of this WebUrlResDto.


        :param web_url: The web_url of this WebUrlResDto.
        :type web_url: str
        """
        if web_url is None:
            raise ValueError("Invalid value for `web_url`, must not be `None`")

        self._web_url = web_url
