services:
  nginx:
    image: windsnow1025/nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "81:80"
    restart: always
    depends_on:
      - next
      - nest
      - fastapi

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    restart: always
    env_file:
      - env/mysql.env
    volumes:
      - mysql_data:/var/lib/mysql

  next:
    image: windsnow1025/next
    build:
      context: ./next
      dockerfile: Dockerfile
    restart: always

  nest:
    image: windsnow1025/nest
    build:
      context: ./nest
      dockerfile: Dockerfile
    restart: always
    env_file:
      - env/nest.env
    depends_on:
      - mysql

  fastapi:
    image: windsnow1025/fastapi
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    restart: always
    env_file:
      - env/fastapi.env
    depends_on:
      - mysql

volumes:
  mysql_data:
