services:
  nginx:
    image: nginx
    ports:
      - "81:80"
    restart: always
    depends_on:
      - next
      - nest
      - fastapi
    volumes:
      - ./config/default.conf:/etc/nginx/conf.d/default.conf:ro

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    restart: always
    env_file:
      - ./env/mysql.env
    volumes:
      - mysql_data:/var/lib/mysql

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: always
    env_file:
      - ./env/minio.env
    environment:
      - MINIO_BROWSER_REDIRECT_URL=http://localhost:81/minio/ui
    volumes:
      - minio_data:/data

  next:
    image: windsnow1025/next
    build:
      context: ./next
      dockerfile: Dockerfile
    restart: always

  nest:
    image: windsnow1025/nest
    build:
      context: ./nest
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./env/nest.env
    depends_on:
      - mysql
      - minio

  fastapi:
    image: windsnow1025/fastapi
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./env/fastapi.env
    depends_on:
      - mysql

volumes:
  mysql_data:
  minio_data:
