services:
  nginx:
    image: nginx

  mysql:
    image: mysql

  minio:
    image: quay.io/minio/minio

  next:
    image: windsnow1025/next
    build:
      context: next
      dockerfile: next/Dockerfile

  nest:
    image: windsnow1025/nest
    build:
      context: nest
      dockerfile: nest/Dockerfile

  fastapi:
    image: windsnow1025/fastapi
    build:
      context: fastapi
      dockerfile: fastapi/Dockerfile
