# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server import util


class AnnouncementResDto(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id: float=None, content: str=None):
        """AnnouncementResDto - a model defined in OpenAPI

        :param id: The id of this AnnouncementResDto.
        :param content: The content of this AnnouncementResDto.
        """
        self.openapi_types = {
            'id': float,
            'content': str
        }

        self.attribute_map = {
            'id': 'id',
            'content': 'content'
        }

        self._id = id
        self._content = content

    @classmethod
    def from_dict(cls, dikt: dict) -> 'AnnouncementResDto':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The AnnouncementResDto of this AnnouncementResDto.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this AnnouncementResDto.


        :return: The id of this AnnouncementResDto.
        :rtype: float
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this AnnouncementResDto.


        :param id: The id of this AnnouncementResDto.
        :type id: float
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")

        self._id = id

    @property
    def content(self):
        """Gets the content of this AnnouncementResDto.


        :return: The content of this AnnouncementResDto.
        :rtype: str
        """
        return self._content

    @content.setter
    def content(self, content):
        """Sets the content of this AnnouncementResDto.


        :param content: The content of this AnnouncementResDto.
        :type content: str
        """
        if content is None:
            raise ValueError("Invalid value for `content`, must not be `None`")

        self._content = content
