# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server import util


class AuthTokenEmailReqDto(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, email: str=None, password: str=None):
        """AuthTokenEmailReqDto - a model defined in OpenAPI

        :param email: The email of this AuthTokenEmailReqDto.
        :param password: The password of this AuthTokenEmailReqDto.
        """
        self.openapi_types = {
            'email': str,
            'password': str
        }

        self.attribute_map = {
            'email': 'email',
            'password': 'password'
        }

        self._email = email
        self._password = password

    @classmethod
    def from_dict(cls, dikt: dict) -> 'AuthTokenEmailReqDto':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The AuthTokenEmailReqDto of this AuthTokenEmailReqDto.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def email(self):
        """Gets the email of this AuthTokenEmailReqDto.


        :return: The email of this AuthTokenEmailReqDto.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this AuthTokenEmailReqDto.


        :param email: The email of this AuthTokenEmailReqDto.
        :type email: str
        """
        if email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")

        self._email = email

    @property
    def password(self):
        """Gets the password of this AuthTokenEmailReqDto.


        :return: The password of this AuthTokenEmailReqDto.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this AuthTokenEmailReqDto.


        :param password: The password of this AuthTokenEmailReqDto.
        :type password: str
        """
        if password is None:
            raise ValueError("Invalid value for `password`, must not be `None`")

        self._password = password
