# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server import util


class AuthTokenUsernameReqDto(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, username: str=None, password: str=None):
        """AuthTokenUsernameReqDto - a model defined in OpenAPI

        :param username: The username of this AuthTokenUsernameReqDto.
        :param password: The password of this AuthTokenUsernameReqDto.
        """
        self.openapi_types = {
            'username': str,
            'password': str
        }

        self.attribute_map = {
            'username': 'username',
            'password': 'password'
        }

        self._username = username
        self._password = password

    @classmethod
    def from_dict(cls, dikt: dict) -> 'AuthTokenUsernameReqDto':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The AuthTokenUsernameReqDto of this AuthTokenUsernameReqDto.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def username(self):
        """Gets the username of this AuthTokenUsernameReqDto.


        :return: The username of this AuthTokenUsernameReqDto.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this AuthTokenUsernameReqDto.


        :param username: The username of this AuthTokenUsernameReqDto.
        :type username: str
        """
        if username is None:
            raise ValueError("Invalid value for `username`, must not be `None`")

        self._username = username

    @property
    def password(self):
        """Gets the password of this AuthTokenUsernameReqDto.


        :return: The password of this AuthTokenUsernameReqDto.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this AuthTokenUsernameReqDto.


        :param password: The password of this AuthTokenUsernameReqDto.
        :type password: str
        """
        if password is None:
            raise ValueError("Invalid value for `password`, must not be `None`")

        self._password = password
