# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server import util


class ConversationPublicReqDto(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, is_public: bool=None):
        """ConversationPublicReqDto - a model defined in OpenAPI

        :param is_public: The is_public of this ConversationPublicReqDto.
        """
        self.openapi_types = {
            'is_public': bool
        }

        self.attribute_map = {
            'is_public': 'isPublic'
        }

        self._is_public = is_public

    @classmethod
    def from_dict(cls, dikt: dict) -> 'ConversationPublicReqDto':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The ConversationPublicReqDto of this ConversationPublicReqDto.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def is_public(self):
        """Gets the is_public of this ConversationPublicReqDto.


        :return: The is_public of this ConversationPublicReqDto.
        :rtype: bool
        """
        return self._is_public

    @is_public.setter
    def is_public(self, is_public):
        """Sets the is_public of this ConversationPublicReqDto.


        :param is_public: The is_public of this ConversationPublicReqDto.
        :type is_public: bool
        """
        if is_public is None:
            raise ValueError("Invalid value for `is_public`, must not be `None`")

        self._is_public = is_public
