# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server import util


class ConversationUpdateTimeResDto(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id: float=None, updated_at: datetime=None):
        """ConversationUpdateTimeResDto - a model defined in OpenAPI

        :param id: The id of this ConversationUpdateTimeResDto.
        :param updated_at: The updated_at of this ConversationUpdateTimeResDto.
        """
        self.openapi_types = {
            'id': float,
            'updated_at': datetime
        }

        self.attribute_map = {
            'id': 'id',
            'updated_at': 'updatedAt'
        }

        self._id = id
        self._updated_at = updated_at

    @classmethod
    def from_dict(cls, dikt: dict) -> 'ConversationUpdateTimeResDto':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The ConversationUpdateTimeResDto of this ConversationUpdateTimeResDto.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this ConversationUpdateTimeResDto.


        :return: The id of this ConversationUpdateTimeResDto.
        :rtype: float
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ConversationUpdateTimeResDto.


        :param id: The id of this ConversationUpdateTimeResDto.
        :type id: float
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")

        self._id = id

    @property
    def updated_at(self):
        """Gets the updated_at of this ConversationUpdateTimeResDto.


        :return: The updated_at of this ConversationUpdateTimeResDto.
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this ConversationUpdateTimeResDto.


        :param updated_at: The updated_at of this ConversationUpdateTimeResDto.
        :type updated_at: datetime
        """
        if updated_at is None:
            raise ValueError("Invalid value for `updated_at`, must not be `None`")

        self._updated_at = updated_at
