# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server.models.message import Message
from openapi_server import util


class ConversationReqDto(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name: str=None, messages: List[Message]=None):
        """ConversationReqDto - a model defined in OpenAPI

        :param name: The name of this ConversationReqDto.
        :param messages: The messages of this ConversationReqDto.
        """
        self.openapi_types = {
            'name': str,
            'messages': List[Message]
        }

        self.attribute_map = {
            'name': 'name',
            'messages': 'messages'
        }

        self._name = name
        self._messages = messages

    @classmethod
    def from_dict(cls, dikt: dict) -> 'ConversationReqDto':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The ConversationReqDto of this ConversationReqDto.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this ConversationReqDto.


        :return: The name of this ConversationReqDto.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ConversationReqDto.


        :param name: The name of this ConversationReqDto.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")

        self._name = name

    @property
    def messages(self):
        """Gets the messages of this ConversationReqDto.


        :return: The messages of this ConversationReqDto.
        :rtype: List[Message]
        """
        return self._messages

    @messages.setter
    def messages(self, messages):
        """Sets the messages of this ConversationReqDto.


        :param messages: The messages of this ConversationReqDto.
        :type messages: List[Message]
        """
        if messages is None:
            raise ValueError("Invalid value for `messages`, must not be `None`")

        self._messages = messages
