# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server import util


class FilesReqDto(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, filenames: List[str]=None):
        """FilesReqDto - a model defined in OpenAPI

        :param filenames: The filenames of this FilesReqDto.
        """
        self.openapi_types = {
            'filenames': List[str]
        }

        self.attribute_map = {
            'filenames': 'filenames'
        }

        self._filenames = filenames

    @classmethod
    def from_dict(cls, dikt: dict) -> 'FilesReqDto':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The FilesReqDto of this FilesReqDto.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def filenames(self):
        """Gets the filenames of this FilesReqDto.


        :return: The filenames of this FilesReqDto.
        :rtype: List[str]
        """
        return self._filenames

    @filenames.setter
    def filenames(self, filenames):
        """Sets the filenames of this FilesReqDto.


        :param filenames: The filenames of this FilesReqDto.
        :type filenames: List[str]
        """
        if filenames is None:
            raise ValueError("Invalid value for `filenames`, must not be `None`")

        self._filenames = filenames
