# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server.models.content import Content
from openapi_server import util


class Message(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, role: str=None, contents: List[Content]=None, thought: str=None, display: str=None):
        """Message - a model defined in OpenAPI

        :param id: The id of this Message.
        :param role: The role of this Message.
        :param contents: The contents of this Message.
        :param thought: The thought of this Message.
        :param display: The display of this Message.
        """
        self.openapi_types = {
            'id': str,
            'role': str,
            'contents': List[Content],
            'thought': str,
            'display': str
        }

        self.attribute_map = {
            'id': 'id',
            'role': 'role',
            'contents': 'contents',
            'thought': 'thought',
            'display': 'display'
        }

        self._id = id
        self._role = role
        self._contents = contents
        self._thought = thought
        self._display = display

    @classmethod
    def from_dict(cls, dikt: dict) -> 'Message':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The Message of this Message.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this Message.


        :return: The id of this Message.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Message.


        :param id: The id of this Message.
        :type id: str
        """

        self._id = id

    @property
    def role(self):
        """Gets the role of this Message.


        :return: The role of this Message.
        :rtype: str
        """
        return self._role

    @role.setter
    def role(self, role):
        """Sets the role of this Message.


        :param role: The role of this Message.
        :type role: str
        """
        allowed_values = ["user", "assistant", "system"]  # noqa: E501
        if role not in allowed_values:
            raise ValueError(
                "Invalid value for `role` ({0}), must be one of {1}"
                .format(role, allowed_values)
            )

        self._role = role

    @property
    def contents(self):
        """Gets the contents of this Message.


        :return: The contents of this Message.
        :rtype: List[Content]
        """
        return self._contents

    @contents.setter
    def contents(self, contents):
        """Sets the contents of this Message.


        :param contents: The contents of this Message.
        :type contents: List[Content]
        """
        if contents is None:
            raise ValueError("Invalid value for `contents`, must not be `None`")

        self._contents = contents

    @property
    def thought(self):
        """Gets the thought of this Message.


        :return: The thought of this Message.
        :rtype: str
        """
        return self._thought

    @thought.setter
    def thought(self, thought):
        """Sets the thought of this Message.


        :param thought: The thought of this Message.
        :type thought: str
        """

        self._thought = thought

    @property
    def display(self):
        """Gets the display of this Message.


        :return: The display of this Message.
        :rtype: str
        """
        return self._display

    @display.setter
    def display(self, display):
        """Sets the display of this Message.


        :param display: The display of this Message.
        :type display: str
        """

        self._display = display
