# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server import util


class ReduceCreditReqDto(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, amount: float=None):
        """ReduceCreditReqDto - a model defined in OpenAPI

        :param amount: The amount of this ReduceCreditReqDto.
        """
        self.openapi_types = {
            'amount': float
        }

        self.attribute_map = {
            'amount': 'amount'
        }

        self._amount = amount

    @classmethod
    def from_dict(cls, dikt: dict) -> 'ReduceCreditReqDto':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The ReduceCreditReqDto of this ReduceCreditReqDto.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def amount(self):
        """Gets the amount of this ReduceCreditReqDto.


        :return: The amount of this ReduceCreditReqDto.
        :rtype: float
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this ReduceCreditReqDto.


        :param amount: The amount of this ReduceCreditReqDto.
        :type amount: float
        """
        if amount is None:
            raise ValueError("Invalid value for `amount`, must not be `None`")
        if amount is not None and amount < 0:
            raise ValueError("Invalid value for `amount`, must be a value greater than or equal to `0`")

        self._amount = amount
