# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server import util


class UserPasswordReqDto(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, password: str=None):
        """UserPasswordReqDto - a model defined in OpenAPI

        :param password: The password of this UserPasswordReqDto.
        """
        self.openapi_types = {
            'password': str
        }

        self.attribute_map = {
            'password': 'password'
        }

        self._password = password

    @classmethod
    def from_dict(cls, dikt: dict) -> 'UserPasswordReqDto':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The UserPasswordReqDto of this UserPasswordReqDto.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def password(self):
        """Gets the password of this UserPasswordReqDto.


        :return: The password of this UserPasswordReqDto.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this UserPasswordReqDto.


        :param password: The password of this UserPasswordReqDto.
        :type password: str
        """
        if password is None:
            raise ValueError("Invalid value for `password`, must not be `None`")

        self._password = password
