# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server import util


class UserResDto(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id: float=None, username: str=None, email: str=None, email_verified: bool=None, roles: List[str]=None, avatar: str=None, credit: float=None):
        """UserResDto - a model defined in OpenAPI

        :param id: The id of this UserResDto.
        :param username: The username of this UserResDto.
        :param email: The email of this UserResDto.
        :param email_verified: The email_verified of this UserResDto.
        :param roles: The roles of this UserResDto.
        :param avatar: The avatar of this UserResDto.
        :param credit: The credit of this UserResDto.
        """
        self.openapi_types = {
            'id': float,
            'username': str,
            'email': str,
            'email_verified': bool,
            'roles': List[str],
            'avatar': str,
            'credit': float
        }

        self.attribute_map = {
            'id': 'id',
            'username': 'username',
            'email': 'email',
            'email_verified': 'emailVerified',
            'roles': 'roles',
            'avatar': 'avatar',
            'credit': 'credit'
        }

        self._id = id
        self._username = username
        self._email = email
        self._email_verified = email_verified
        self._roles = roles
        self._avatar = avatar
        self._credit = credit

    @classmethod
    def from_dict(cls, dikt: dict) -> 'UserResDto':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The UserResDto of this UserResDto.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this UserResDto.


        :return: The id of this UserResDto.
        :rtype: float
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this UserResDto.


        :param id: The id of this UserResDto.
        :type id: float
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")

        self._id = id

    @property
    def username(self):
        """Gets the username of this UserResDto.


        :return: The username of this UserResDto.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this UserResDto.


        :param username: The username of this UserResDto.
        :type username: str
        """
        if username is None:
            raise ValueError("Invalid value for `username`, must not be `None`")

        self._username = username

    @property
    def email(self):
        """Gets the email of this UserResDto.


        :return: The email of this UserResDto.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this UserResDto.


        :param email: The email of this UserResDto.
        :type email: str
        """
        if email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")

        self._email = email

    @property
    def email_verified(self):
        """Gets the email_verified of this UserResDto.


        :return: The email_verified of this UserResDto.
        :rtype: bool
        """
        return self._email_verified

    @email_verified.setter
    def email_verified(self, email_verified):
        """Sets the email_verified of this UserResDto.


        :param email_verified: The email_verified of this UserResDto.
        :type email_verified: bool
        """
        if email_verified is None:
            raise ValueError("Invalid value for `email_verified`, must not be `None`")

        self._email_verified = email_verified

    @property
    def roles(self):
        """Gets the roles of this UserResDto.


        :return: The roles of this UserResDto.
        :rtype: List[str]
        """
        return self._roles

    @roles.setter
    def roles(self, roles):
        """Sets the roles of this UserResDto.


        :param roles: The roles of this UserResDto.
        :type roles: List[str]
        """
        allowed_values = ["user", "admin"]  # noqa: E501
        if not set(roles).issubset(set(allowed_values)):
            raise ValueError(
                "Invalid values for `roles` [{0}], must be a subset of [{1}]"
                .format(", ".join(map(str, set(roles) - set(allowed_values))),
                        ", ".join(map(str, allowed_values)))
            )

        self._roles = roles

    @property
    def avatar(self):
        """Gets the avatar of this UserResDto.


        :return: The avatar of this UserResDto.
        :rtype: str
        """
        return self._avatar

    @avatar.setter
    def avatar(self, avatar):
        """Sets the avatar of this UserResDto.


        :param avatar: The avatar of this UserResDto.
        :type avatar: str
        """

        self._avatar = avatar

    @property
    def credit(self):
        """Gets the credit of this UserResDto.


        :return: The credit of this UserResDto.
        :rtype: float
        """
        return self._credit

    @credit.setter
    def credit(self, credit):
        """Sets the credit of this UserResDto.


        :param credit: The credit of this UserResDto.
        :type credit: float
        """
        if credit is None:
            raise ValueError("Invalid value for `credit`, must not be `None`")

        self._credit = credit
