apiVersion: v1
kind: Service
metadata:
  name: nest-service
  labels:
    app: nest
spec:
  type: ClusterIP
  selector:
    app: nest
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000