### Get API Models

GET {{baseUrl}}/model

### Post Chat

POST {{baseUrl}}/chat
Content-Type: application/json
Authorization: {{token}}

{
  "messages": [
    {
      "role": "user",
      "contents": [
        {
          "type": "text",
          "data": "Explain the concept of Occam's Razor and provide a simple, everyday example."
        }
      ]
    }
  ],
  "model": "claude-sonnet-4-5",
  "api_type": "Claude",
  "temperature": 0,
  "stream": true,
  "thought": true,
  "code_execution": true
}
