### Post DALL·E

POST {{baseUrl}}/image-gen
Content-Type: application/json
Authorization: {{token}}

{
  "prompt": "a white siamese cat",
  "model": "dall-e-3",
  "size": "1024x1024",
  "quality": "standard",
  "n": 1
}
