version: '3'

services:
  react:
    image: react
    ports:
      - "3000:3000"
    restart: always

  node:
    image: node
    ports:
      - "8000:3000"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=<MYSQL_ROOT_PASSWORD>
      - MYSQL_USER=<MYSQL_USER>
      - MYSQL_PASSWORD=<MYSQL_PASSWORD>
      - MYSQL_DATABASE=<MYSQL_DATABASE>
      - JWT_SECRET=<JWT_SECRET>

  flask:
    image: flask
    ports:
      - "5000:5000"
    restart: always
    environment:
      - OPENAI_API_KEY=<OPENAI_API_KEY>
      - JWT_SECRET=<JWT_SECRET>

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=<MYSQL_ROOT_PASSWORD>
      - MYSQL_USER=<MYSQL_USER>
      - MYSQL_PASSWORD=<MYSQL_PASSWORD>
      - MYSQL_DATABASE=<MYSQL_DATABASE>
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
