### Get Announcement

GET {{baseUrl}}/announcement

### Update Announcement

PUT {{baseUrl}}/announcement
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "content": "announcement 1"
}
