### Get Bookmarks

GET {{baseUrl}}/bookmarks

### Create Bookmark

POST {{baseUrl}}/bookmarks/bookmark
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "firstTitle": "test first title",
  "secondTitle": "test second title",
  "url": "test url",
  "comment": "test comment"
}

### Update Bookmark

PUT {{baseUrl}}/bookmarks/bookmark
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id": "1",
  "firstTitle": "test first title 1",
  "secondTitle": "test second title 1",
  "url": "test url 1",
  "comment": "test comment 1"
}

### Delete Bookmark

DELETE {{baseUrl}}/bookmarks/bookmark/1
Authorization: Bearer {{token}}
