### Get Bookmarks

GET {{baseUrl}}/markdowns

### Get Bookmarks

GET {{baseUrl}}/markdowns/markdown/1

### Create Bookmark

POST {{baseUrl}}/markdowns/markdown
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "test title",
  "content": "test content"
}

### Update Bookmark

PUT {{baseUrl}}/markdowns/markdown
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id": 1,
  "title": "test title 1",
  "content": "test content 1"
}

### Delete Bookmark

DELETE {{baseUrl}}/markdowns/markdown/1
Authorization: Bearer {{token}}
