### Get Messages

GET {{baseUrl}}/messages

### Create Message

POST {{baseUrl}}/messages/message
Content-Type: application/json

{
  "username": "test",
  "content": "test content"
}

### Delete Message

DELETE {{baseUrl}}/messages
