### Get User

GET {{baseUrl}}/users/user
Authorization: Bearer {{token}}

### Sign Up

POST {{baseUrl}}/users/user
Content-Type: application/json

{
  "username": "test",
  "password": "test"
}

### Delete

DELETE {{baseUrl}}/users/user
Authorization: Bearer {{token}}
