### Get Users

GET {{baseUrl}}/users
Authorization: Bearer {{token}}

### Get User

GET {{baseUrl}}/users/user
Authorization: Bearer {{token}}

### Sign Up

POST {{baseUrl}}/users/user
Content-Type: application/json

{
  "username": "test",
  "email": "test@test.com",
  "password": "test"
}

### Send Email Verification

POST {{baseUrl}}/users/user/email-verification
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "test"
}

### Update Email Verified

PUT {{baseUrl}}/users/user/email-verified
Content-Type: application/json

{
  "username": "test",
  "email": "test@test.com",
  "password": "test"
}

### Update Username

PUT {{baseUrl}}/users/user/username
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "username": "test"
}

### Update Email

PUT {{baseUrl}}/users/user/email
Content-Type: application/json

{
  "username": "test",
  "email": "test@test.com",
  "password": "test"
}

### Update Password

PUT {{baseUrl}}/users/user/password
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "password": "test"
}

### Admin: Update User Privileges

PUT {{baseUrl}}/users/user/privileges
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "username": "test",
  "roles": ["admin"],
  "credit": 100
}

### Delete User

DELETE {{baseUrl}}/users/user
Authorization: Bearer {{token}}

### Admin: Delete User

DELETE {{baseUrl}}/users/user/2
Authorization: Bearer {{token}}
