apiVersion: v1
kind: Service
metadata:
  name: next-service
  labels:
    app: next
spec:
  type: ClusterIP
  selector:
    app: next
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000