apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-deployment
  labels:
    app: next
spec:
  replicas: 1
  selector:
    matchLabels:
      app: next
  template:
    metadata:
      labels:
        app: next
    spec:
      containers:
        - name: next
          image: windsnow1025/next:${IMAGE_TAG}
          ports:
            - containerPort: 3000
          env:
            - name: IMAGE_TAG
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: IMAGE_TAG
  revisionHistoryLimit: 0
