version: '3'

services:
  nginx:
    image: windsnow1025/nginx
    ports:
      - "80:80"
    restart: always

  react:
    image: react
    restart: always

  node:
    image: node
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=<MYSQL_ROOT_PASSWORD>
      - MYSQL_USER=<MYSQL_USER>
      - MYSQL_PASSWORD=<MYSQL_PASSWORD>
      - MYSQL_DATABASE=<MYSQL_DATABASE>
      - JWT_SECRET=<JWT_SECRET>
    depends_on:
      - mysql

  fastapi:
    image: fastapi
    restart: always
    environment:
      - JWT_SECRET=<JWT_SECRET>
      - OPENAI_API_KEY=<OPENAI_API_KEY>
      - AZURE_API_KEY=<AZURE_API_KEY>
      - AZURE_API_BASE=<AZURE_API_BASE>

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=<MYSQL_ROOT_PASSWORD>
      - MYSQL_USER=<MYSQL_USER>
      - MYSQL_PASSWORD=<MYSQL_PASSWORD>
      - MYSQL_DATABASE=<MYSQL_DATABASE>
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
