/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface ChatRequest {
    'messages': Array<Message>;
    'api_type': string;
    'model': string;
    'temperature': number;
    'stream': boolean;
    'thought': boolean;
    'code_execution': boolean;
    'structured_output_schema'?: object | null;
}
export interface Content {
    'type': ContentType;
    'data': string;
}



export const ContentType = {
    Text: 'text',
    File: 'file'
} as const;

export type ContentType = typeof ContentType[keyof typeof ContentType];


export interface HTTPValidationError {
    'detail'?: Array<ValidationError>;
}
export interface Message {
    'role': Role;
    'contents': Array<Content>;
}


export interface MessagesConvertRequest {
    'messages': Array<Message>;
    'api_type': string;
}
export interface ModelPrice {
    'apiType': string;
    'model': string;
    'input': number;
    'output': number;
}

export const Role = {
    User: 'user',
    Assistant: 'assistant',
    System: 'system'
} as const;

export type Role = typeof Role[keyof typeof Role];


export interface ValidationError {
    'loc': Array<ValidationErrorLocInner>;
    'msg': string;
    'type': string;
}
export interface ValidationErrorLocInner {
}

/**
 * DefaultApi - axios parameter creator
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Convert Messages
         * @param {MessagesConvertRequest} messagesConvertRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        convertMessagesMessagesConvertPost: async (messagesConvertRequest: MessagesConvertRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'messagesConvertRequest' is not null or undefined
            assertParamExists('convertMessagesMessagesConvertPost', 'messagesConvertRequest', messagesConvertRequest)
            const localVarPath = `/messages/convert`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(messagesConvertRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Generate
         * @param {ChatRequest} chatRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        generateChatPost: async (chatRequest: ChatRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'chatRequest' is not null or undefined
            assertParamExists('generateChatPost', 'chatRequest', chatRequest)
            const localVarPath = `/chat`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(chatRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Models
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getModelsModelGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/model`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Convert Messages
         * @param {MessagesConvertRequest} messagesConvertRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async convertMessagesMessagesConvertPost(messagesConvertRequest: MessagesConvertRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.convertMessagesMessagesConvertPost(messagesConvertRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.convertMessagesMessagesConvertPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Generate
         * @param {ChatRequest} chatRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async generateChatPost(chatRequest: ChatRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.generateChatPost(chatRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.generateChatPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get Models
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getModelsModelGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ModelPrice>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getModelsModelGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getModelsModelGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @summary Convert Messages
         * @param {MessagesConvertRequest} messagesConvertRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        convertMessagesMessagesConvertPost(messagesConvertRequest: MessagesConvertRequest, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.convertMessagesMessagesConvertPost(messagesConvertRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Generate
         * @param {ChatRequest} chatRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        generateChatPost(chatRequest: ChatRequest, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.generateChatPost(chatRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get Models
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getModelsModelGet(options?: RawAxiosRequestConfig): AxiosPromise<Array<ModelPrice>> {
            return localVarFp.getModelsModelGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary Convert Messages
     * @param {MessagesConvertRequest} messagesConvertRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public convertMessagesMessagesConvertPost(messagesConvertRequest: MessagesConvertRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).convertMessagesMessagesConvertPost(messagesConvertRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Generate
     * @param {ChatRequest} chatRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public generateChatPost(chatRequest: ChatRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).generateChatPost(chatRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get Models
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getModelsModelGet(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getModelsModelGet(options).then((request) => request(this.axios, this.basePath));
    }
}



