apiVersion: v1
kind: Service
metadata:
  name: minio-service
  labels:
    app: minio
spec:
  type: NodePort
  selector:
    app: minio
  ports:
    - name: minio-api
      protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 39000
    - name: minio-console
      protocol: TCP
      port: 9001
      targetPort: 9001
      nodePort: 39001
