### Post OpenAI Stream Text

POST {{baseUrl}}/
Content-Type: application/json
Authorization: {{token}}

{
  "messages": [
    {
      "role": "user",
      "text": "Say this is a test.",
      "files": []
    }
  ],
  "model": "gpt-4-turbo",
  "api_type": "open_ai",
  "temperature": 0,
  "stream": true
}

### Post OpenAI Stream Image

POST {{baseUrl}}/
Content-Type: application/json
Authorization: {{token}}

{
  "messages": [
    {
      "role": "user",
      "text": "What's in this image?",
      "files": [
        "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Gfp-wisconsin-madison-the-nature-boardwalk.jpg/2560px-Gfp-wisconsin-madison-the-nature-boardwalk.jpg"
      ]
    }
  ],
  "model": "gpt-4-turbo",
  "api_type": "open_ai",
  "temperature": 0,
  "stream": true
}

### Post Gemini Stream Text

POST {{baseUrl}}/
Content-Type: application/json
Authorization: {{token}}

{
  "messages": [
    {
      "role": "user",
      "text": "Say this is a test.",
      "files": []
    }
  ],
  "model": "gemini-1.5-pro-latest",
  "api_type": "gemini",
  "temperature": 0,
  "stream": true
}


### Post Gemini Stream Image

POST {{baseUrl}}/
Content-Type: application/json
Authorization: {{token}}

{
  "messages": [
    {
      "role": "user",
      "text": "What's in this image?",
      "files": [
        "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Gfp-wisconsin-madison-the-nature-boardwalk.jpg/2560px-Gfp-wisconsin-madison-the-nature-boardwalk.jpg"
      ]
    }
  ],
  "model": "gemini-1.5-pro-latest",
  "api_type": "gemini",
  "temperature": 0,
  "stream": true
}
