name: Docker deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy files to server
        run: |
          scp ./docker-compose.yaml root@${{ secrets.SERVER_ADDRESS }}:/root/UniWebPlatform/

      - name: Deploy with Docker Compose
        run: |
          ssh root@${{ secrets.SERVER_ADDRESS }} 'cd /root/UniWebPlatform/ && docker-compose pull && docker-compose up -d'